export { default as DPessoaisE } from './DPessoaisE'
export { default as DPessoaisE2 } from './DPessoaisE2'
export { default as DAcademicos } from './DAcademicos'
export { default as DLogin } from './DLoginE'
export { default as CadastroHeaderE } from './Header'