/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/telaCadastro`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/content/mainEstudante`; params?: Router.UnknownInputParams; } | { pathname: `/content/mainEstudanteEmpty`; params?: Router.UnknownInputParams; } | { pathname: `/content/telasEstudante/avisosHistorico`; params?: Router.UnknownInputParams; } | { pathname: `/content/telasEstudante/buscarRotas`; params?: Router.UnknownInputParams; } | { pathname: `/content/telasEstudante/calendario`; params?: Router.UnknownInputParams; } | { pathname: `/content/telasEstudante/minhasRotas`; params?: Router.UnknownInputParams; } | { pathname: `/content/telasEstudante/presencas`; params?: Router.UnknownInputParams; } | { pathname: `/content/telasEstudante/rotaFavorita`; params?: Router.UnknownInputParams; } | { pathname: `/content/telasEstudante/solicitadas`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/telaCadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/content/mainEstudante`; params?: Router.UnknownOutputParams; } | { pathname: `/content/mainEstudanteEmpty`; params?: Router.UnknownOutputParams; } | { pathname: `/content/telasEstudante/avisosHistorico`; params?: Router.UnknownOutputParams; } | { pathname: `/content/telasEstudante/buscarRotas`; params?: Router.UnknownOutputParams; } | { pathname: `/content/telasEstudante/calendario`; params?: Router.UnknownOutputParams; } | { pathname: `/content/telasEstudante/minhasRotas`; params?: Router.UnknownOutputParams; } | { pathname: `/content/telasEstudante/presencas`; params?: Router.UnknownOutputParams; } | { pathname: `/content/telasEstudante/rotaFavorita`; params?: Router.UnknownOutputParams; } | { pathname: `/content/telasEstudante/solicitadas`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/telaCadastro${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/content/mainEstudante${`?${string}` | `#${string}` | ''}` | `/content/mainEstudanteEmpty${`?${string}` | `#${string}` | ''}` | `/content/telasEstudante/avisosHistorico${`?${string}` | `#${string}` | ''}` | `/content/telasEstudante/buscarRotas${`?${string}` | `#${string}` | ''}` | `/content/telasEstudante/calendario${`?${string}` | `#${string}` | ''}` | `/content/telasEstudante/minhasRotas${`?${string}` | `#${string}` | ''}` | `/content/telasEstudante/presencas${`?${string}` | `#${string}` | ''}` | `/content/telasEstudante/rotaFavorita${`?${string}` | `#${string}` | ''}` | `/content/telasEstudante/solicitadas${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/telaCadastro`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/content/mainEstudante`; params?: Router.UnknownInputParams; } | { pathname: `/content/mainEstudanteEmpty`; params?: Router.UnknownInputParams; } | { pathname: `/content/telasEstudante/avisosHistorico`; params?: Router.UnknownInputParams; } | { pathname: `/content/telasEstudante/buscarRotas`; params?: Router.UnknownInputParams; } | { pathname: `/content/telasEstudante/calendario`; params?: Router.UnknownInputParams; } | { pathname: `/content/telasEstudante/minhasRotas`; params?: Router.UnknownInputParams; } | { pathname: `/content/telasEstudante/presencas`; params?: Router.UnknownInputParams; } | { pathname: `/content/telasEstudante/rotaFavorita`; params?: Router.UnknownInputParams; } | { pathname: `/content/telasEstudante/solicitadas`; params?: Router.UnknownInputParams; };
    }
  }
}
